modified

diff --git a/.github/workflows/branch_protection.yaml b/.github/workflows/branch_protection.yaml
--- a/.github/workflows/branch_protection.yaml
+++ b/.github/workflows/branch_protection.yaml
@@ -26,13 +26,13 @@ jobs:
         REPO_NAME: ${{ secrets.REPO_NAME }}
         DEPLOY_BRANCH: ${{ secrets.DEPLOY_BRANCH }}
 
-  check_deploy_branch:
-    name: Restrict Production Deployments
-    runs-on: ubuntu-latest
-    if: github.ref != 'refs/heads/main'  # Ensure this job only runs if not on main branch
+#  check_deploy_branch:
+ #   name: Restrict Production Deployments
+  #  runs-on: ubuntu-latest
+   # if: github.ref != 'refs/heads/main'  # Ensure this job only runs if not on main branch
 
-    steps:
-    - name: Fail if not deploying from main
-      run: |
-        echo "Deployments are only allowed from the main branch."
-        exit 1
+    #steps:
+#    - name: Fail if not deploying from main
+ #     run: |
+  #      echo "Deployments are only allowed from the main branch."
+   #     exit 1
